# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20201208_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_de_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
