# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-08 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_auto_20201208_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_de_inicio',
            field=models.DateField(verbose_name=datetime.datetime(2020, 12, 8, 21, 50, 40, 396000, tzinfo=utc)),
        ),
    ]
