# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-08 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_auto_20201208_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_de_inicio',
            field=models.DateField(verbose_name=datetime.datetime(2020, 12, 8, 22, 1, 26, 164000, tzinfo=utc)),
        ),
    ]
