# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-09 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_auto_20201208_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_de_inicio',
            field=models.DateField(verbose_name=datetime.datetime(2020, 12, 9, 13, 12, 1, 38000, tzinfo=utc)),
        ),
    ]
