# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
